
import styles from "./globals.css";
import NavBar from "./components/navBar";

export const metadata = {
  title: "QueenB mentoring matching app", 
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <div className={styles.navbar}>
          <NavBar/>
        </div>
        <div className={styles.children}>
          {children}
        </div>
      </body>
    </html>
  );
}
